version: '3'
services:
  discovery-service:
    build: ./discovery-service
    ports: ["8761:8761"]
  api-gateway:
    build: ./api-gateway
    ports: ["8080:8080"]
  product-service:
    build: ./product-service
    ports: ["8081:8081"]
  order-service:
    build: ./order-service
    ports: ["8082:8082"]
